apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentrydash-frontend
  namespace: sentrydash
  labels:
    app: sentrydash-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentrydash-frontend
  template:
    metadata:
      labels:
        app: sentrydash-frontend
    spec:
      containers:
        - name: sentrydash-frontend
          image: sentrydash2204.azurecr.io/sentrydash-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
